### ISSUE TITLE
[core/usability]: Improve Select Operation Syntax

### ISSUE THREAD

**Issue by leonmeka** [leonmeka/monk-cli#10]
Currently, the `select` operation works by filtering file paths via a regex pattern. To allow selecting files to operate on more flexible and intuitive, the select operation should follow a sql-like syntax:

e.g.:

```
- action: select
  where:
      - path: pattern
      - extension: pattern
      - size: pattern
      - created: pattern
      - modified: pattern
  then:
      - action: name
```

For now, we'll limit the scope to filter for:
- path: Pattern to match the file name including its relative path (e.g.: '*/music/*')
- extension: Pattern to match the file extension (e.g.: "pdf")
- size: Pattern to allow comparative operators on file sizes (e.g. "<= 500mb", "> 1gb")
- created: Pattern to allow comparative operators on [RFC 3339](https://tools.ietf.org/html/rfc3339) timestamps (e.g. "<= 2024-03-04T21:17:56+00:00")
- modified: Pattern to allow comparative operators on [RFC 3339](https://tools.ietf.org/html/rfc3339) timestamps (e.g. "<= 2024-03-04T21:17:56+00:00")
